version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stp_backend
    ports:
      - "8001:8001"
    restart: always
    environment:
      - PORT=8001

  frontend:
    build:
      context: ./frontend/stp-app
      dockerfile: Dockerfile
    container_name: stp_frontend
    ports:
      - "5173:80"
    restart: always
    depends_on:
      - backend

  router_service:
    build:
      context: ./router_service
      dockerfile: Dockerfile
    container_name: stp_router_service
    ports:
      - "5002:5002"
    restart: always
    volumes:
      - /home/routeruser/5grouter_images:/home/routeruser/5grouter_images
      - /home/routeruser/cam2images:/home/routeruser/cam2images

