import React, { useState, useEffect } from 'react';
import {
  Camera, RefreshCw, ChevronLeft, ChevronRight, UserCheck, ShieldCheck,
  UserPlus, CheckCircle2, Clock, AlertCircle, EyeOff, Lock, User, AlertTriangle, FileImage
} from 'lucide-react';
import { TelemetryAPI } from '../api';

interface CameraChannel {
  id: string;
  name: string;
  location: string;
  aws_path: string;
  status: string;
  image_url: string;
  last_updated: string;
}

interface StaffMember {
  id: string;
  name: string;
  role: string;
  status: string;
  activeCount: number;
}

interface LogEntry {
  time: string;
  text: string;
  type: 'info' | 'warning' | 'success';
}

interface CameraMonitoringProps {
  deviceId: string;
  deviceName?: string;
}

export const CameraMonitoring: React.FC<CameraMonitoringProps> = ({ deviceId, deviceName }) => {
  const [selectedCameraId, setSelectedCameraId] = useState<string>('cam_01');
  const [aiEnabled, setAiEnabled] = useState<boolean>(true);
  const [activeSnapshotIdx, setActiveSnapshotIdx] = useState<number>(0);
  const [refreshing, setRefreshing] = useState<boolean>(false);
  const [systemTime, setSystemTime] = useState<string>('');
  const [imageLoadFailed, setImageLoadFailed] = useState<boolean>(false);
  const [customFilename, setCustomFilename] = useState<string>('latest.jpg');

  // AWS EC2 13.200.3.124 Remote Image Paths
  const awsHost = 'http://13.200.3.124';

  // Common file name patterns generated by 5G routers and security cameras
  const filenameOptions = [
    'latest.jpg',
    'image.jpg',
    'snapshot.jpg',
    'cam1.jpg',
    'cam2.jpg',
    '1.jpg',
    '2.jpg',
    '0.jpg',
    'photo.jpg',
    'capture.jpg'
  ];

  const activeFolder = selectedCameraId === 'cam_01' ? '5grouter_images' : 'cam2images';
  const activePath = `/home/routeruser/${activeFolder}`;
  const activeBaseUrl = `${awsHost}/${activeFolder}/`;

  const authorizedStaff: StaffMember[] = [
    { id: '1', name: 'Saguaru', role: 'Visitor', status: 'ACTIVE', activeCount: 1 },
    { id: '2', name: 'El Presidento', role: 'Operator', status: 'ACTIVE', activeCount: 1 },
  ];

  const identificationLogs: LogEntry[] = [
    { time: '12:12:59', text: `AWS Stream Targeted: ${awsHost}/${activeFolder}/${customFilename}`, type: 'info' },
    { time: '12:10:30', text: 'Detected Authorized: El Presidento (Operator)', type: 'success' },
    { time: '07:02:50', text: 'Detected Unknown / Unauthorized Presence', type: 'warning' },
  ];

  useEffect(() => {
    const updateTime = () => {
      setSystemTime(new Date().toLocaleTimeString('en-US', { hour12: false }));
    };
    updateTime();
    const interval = setInterval(updateTime, 1000);
    return () => clearInterval(interval);
  }, []);

  const activeImageUrl = `${activeBaseUrl}${customFilename}`;

  const handleRefresh = () => {
    setRefreshing(true);
    setImageLoadFailed(false);
    setTimeout(() => setRefreshing(false), 500);
  };

  return (
    <div style={{ fontFamily: 'Inter, system-ui, sans-serif', color: '#0F172A', display: 'flex', flexDirection: 'column', gap: '20px' }}>
      
      {/* Header Bar */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: '16px'
      }}>
        <div>
          <h1 style={{ fontSize: '24px', fontWeight: 800, color: '#0F172A', margin: 0, letterSpacing: '-0.5px' }}>
            CAMERA MONITORING
          </h1>
          <p style={{ fontSize: '13px', color: '#64748B', margin: '2px 0 0 0' }}>
            Live AWS Remote Stream (IP: <code>13.200.3.124</code>)
          </p>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '14px', flexWrap: 'wrap' }}>
          {/* AWS Server Path Tag */}
          <span style={{
            fontSize: '11px',
            fontFamily: 'monospace',
            background: '#F0F9FF',
            color: '#0284C7',
            border: '1px solid #BAE6FD',
            padding: '6px 12px',
            borderRadius: '8px',
            fontWeight: 700
          }}>
            📂 {activePath}
          </span>

          {/* Camera Selector Dropdown */}
          <div style={{ position: 'relative' }}>
            <select
              value={selectedCameraId}
              onChange={(e) => {
                setSelectedCameraId(e.target.value);
                setActiveSnapshotIdx(0);
                setImageLoadFailed(false);
              }}
              style={{
                padding: '8px 36px 8px 16px',
                borderRadius: '8px',
                border: '1px solid #CBD5E1',
                background: '#FFFFFF',
                color: '#0F172A',
                fontSize: '13px',
                fontWeight: 700,
                cursor: 'pointer',
                outline: 'none',
                appearance: 'none'
              }}
            >
              <option value="cam_01">CAMERA 1 (5grouter_images)</option>
              <option value="cam_02">CAMERA 2 (cam2images)</option>
            </select>
            <span style={{ position: 'absolute', right: '12px', top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none', fontSize: '10px' }}>▼</span>
          </div>

          {/* Image Filename Selector */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
            <FileImage size={15} color="#0284C7" />
            <select
              value={customFilename}
              onChange={(e) => {
                setCustomFilename(e.target.value);
                setImageLoadFailed(false);
              }}
              style={{
                padding: '7px 12px',
                borderRadius: '8px',
                border: '1px solid #0284C7',
                background: '#F0F9FF',
                color: '#0369A1',
                fontSize: '12px',
                fontWeight: 700,
                cursor: 'pointer',
                outline: 'none'
              }}
            >
              {filenameOptions.map((fn) => (
                <option key={fn} value={fn}>
                  📄 {fn}
                </option>
              ))}
            </select>
          </div>

          {/* Refresh Button */}
          <button
            onClick={handleRefresh}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              padding: '8px 16px',
              borderRadius: '8px',
              border: '1px solid #CBD5E1',
              background: '#FFFFFF',
              color: '#0F172A',
              fontSize: '12px',
              fontWeight: 700,
              cursor: 'pointer'
            }}
          >
            <RefreshCw size={14} style={{ animation: refreshing ? 'spin 1s linear infinite' : 'none' }} />
            REFRESH
          </button>
        </div>
      </div>

      {/* Main 2-Column Dashboard Layout */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'minmax(0, 1.8fr) minmax(320px, 1fr)',
        gap: '24px',
        alignItems: 'start'
      }}>

        {/* LEFT COLUMN: Main AWS Snapshot Viewer + Filename Strip */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
          
          {/* Snapshot Viewer Box */}
          <div style={{
            position: 'relative',
            width: '100%',
            background: '#090D16',
            borderRadius: '16px',
            overflow: 'hidden',
            boxShadow: '0 12px 36px rgba(15, 23, 42, 0.2)',
            aspectRatio: '16/9',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center'
          }}>
            {/* Top OSD Date / Time */}
            <div style={{
              position: 'absolute',
              top: '16px',
              left: '20px',
              color: '#FFFFFF',
              fontFamily: 'monospace',
              fontSize: '14px',
              fontWeight: 700,
              textShadow: '0 2px 4px rgba(0,0,0,0.8)',
              zIndex: 10
            }}>
              13 - Aug - 2026 &nbsp; {systemTime || '12 : 12 : 59 PM'}
            </div>

            {/* Top Right Path Badge */}
            <div style={{
              position: 'absolute',
              top: '16px',
              right: '20px',
              background: 'rgba(15, 23, 42, 0.85)',
              backdropFilter: 'blur(6px)',
              padding: '4px 12px',
              borderRadius: '20px',
              color: '#38BDF8',
              fontFamily: 'monospace',
              fontSize: '11px',
              fontWeight: 700,
              border: '1px solid rgba(56, 189, 248, 0.3)',
              zIndex: 10
            }}>
              {activeFolder}/{customFilename}
            </div>

            {/* AWS Snapshot Image Rendering */}
            {!imageLoadFailed ? (
              <img
                src={activeImageUrl}
                alt={`AWS Snapshot ${customFilename}`}
                onError={() => setImageLoadFailed(true)}
                style={{
                  width: '100%',
                  height: '100%',
                  objectFit: 'cover',
                  display: 'block'
                }}
              />
            ) : (
              /* AWS Image Path Info HUD Card */
              <div style={{
                textAlign: 'center',
                padding: '30px',
                color: '#F8FAFC',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                gap: '12px'
              }}>
                <AlertTriangle size={42} color="#F59E0B" />
                <h4 style={{ margin: 0, fontSize: '16px', fontWeight: 800 }}>AWS Remote Feed Target Active</h4>
                <p style={{ margin: 0, fontSize: '12px', color: '#94A3B8', maxWidth: '440px', lineHeight: '1.6' }}>
                  Attempting to fetch live image from AWS server <strong>13.200.3.124</strong>:
                  <br />
                  <code style={{ color: '#38BDF8', background: '#1E293B', padding: '6px 12px', borderRadius: '8px', display: 'inline-block', marginTop: '8px', wordBreak: 'break-all' }}>
                    {activeImageUrl}
                  </code>
                </p>
              </div>
            )}

            {/* Bottom Left OSD Tag */}
            <div style={{
              position: 'absolute',
              bottom: '16px',
              left: '20px',
              display: 'flex',
              alignItems: 'center',
              gap: '12px',
              fontFamily: 'monospace',
              fontSize: '12px',
              color: '#FF6B00',
              fontWeight: 700,
              zIndex: 10
            }}>
              <span>📅 13/Aug/2026</span>
              <span>🕒 {systemTime}</span>
            </div>

            {/* Bottom Center ROOM SECURED Badge */}
            <div style={{
              position: 'absolute',
              bottom: '16px',
              left: '50%',
              transform: 'translateX(-50%)',
              background: 'rgba(16, 185, 129, 0.25)',
              border: '1px solid #10B981',
              backdropFilter: 'blur(6px)',
              padding: '6px 16px',
              borderRadius: '8px',
              color: '#34D399',
              fontSize: '12px',
              fontWeight: 800,
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              letterSpacing: '0.5px',
              zIndex: 10
            }}>
              <ShieldCheck size={16} />
              ROOM SECURED
            </div>
          </div>

          {/* Bottom Filename Quick Selection Strip */}
          <div style={{
            display: 'flex',
            gap: '10px',
            overflowX: 'auto',
            padding: '8px 2px',
            scrollbarWidth: 'thin'
          }}>
            {filenameOptions.slice(0, 5).map((fn) => (
              <div
                key={fn}
                onClick={() => {
                  setCustomFilename(fn);
                  setImageLoadFailed(false);
                }}
                style={{
                  minWidth: '110px',
                  height: '55px',
                  borderRadius: '8px',
                  cursor: 'pointer',
                  border: customFilename === fn ? '2px solid #0284C7' : '1px solid #CBD5E1',
                  background: customFilename === fn ? '#F0F9FF' : '#FFFFFF',
                  color: customFilename === fn ? '#0369A1' : '#475569',
                  transition: 'all 0.2s',
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: '4px',
                  padding: '6px'
                }}
              >
                <FileImage size={16} />
                <span style={{ fontSize: '11px', fontWeight: 700, fontFamily: 'monospace' }}>
                  {fn}
                </span>
              </div>
            ))}
          </div>

        </div>


        {/* RIGHT COLUMN: AI Face Identification & Database Panels */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
          
          {/* Card 1: AI FACE IDENTIFICATION Toggle */}
          <div style={{
            background: '#FFFFFF',
            borderRadius: '14px',
            border: '1px solid #E2E8F0',
            padding: '16px 20px',
            boxShadow: '0 2px 10px rgba(0,0,0,0.02)',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center'
          }}>
            <div>
              <h4 style={{ fontSize: '15px', fontWeight: 800, color: '#0284C7', margin: 0, letterSpacing: '-0.3px' }}>
                AI FACE IDENTIFICATION
              </h4>
              <p style={{ fontSize: '11px', color: '#64748B', margin: '2px 0 0 0' }}>
                Match faces to employee database
              </p>
            </div>

            {/* Toggle Switch */}
            <div
              onClick={() => setAiEnabled(!aiEnabled)}
              style={{
                width: '46px',
                height: '24px',
                borderRadius: '12px',
                background: aiEnabled ? '#FF6B00' : '#CBD5E1',
                padding: '2px',
                cursor: 'pointer',
                transition: 'background 0.2s',
                display: 'flex',
                alignItems: 'center'
              }}
            >
              <div style={{
                width: '20px',
                height: '20px',
                borderRadius: '50%',
                background: '#FFFFFF',
                transform: aiEnabled ? 'translateX(22px)' : 'translateX(0px)',
                transition: 'transform 0.2s',
                boxShadow: '0 2px 4px rgba(0,0,0,0.2)'
              }} />
            </div>
          </div>


          {/* Card 2: DETECTIONS IN PHOTO */}
          <div style={{
            background: '#F5F3FF',
            borderRadius: '14px',
            border: '1px solid #DDD6FE',
            padding: '18px 20px',
            display: 'flex',
            flexDirection: 'column',
            gap: '10px'
          }}>
            <h4 style={{ fontSize: '13px', fontWeight: 800, color: '#6D28D9', margin: 0, display: 'flex', alignItems: 'center', gap: '6px' }}>
              <span>🔍</span> DETECTIONS IN PHOTO
            </h4>

            <div style={{
              textAlign: 'center',
              padding: '24px 12px',
              color: '#6D28D9',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              gap: '8px'
            }}>
              <EyeOff size={32} color="#A78BFA" />
              <span style={{ fontSize: '13px', fontWeight: 700 }}>No persons detected in snapshot.</span>
            </div>
          </div>


          {/* Card 3: AUTHORIZED STAFF DATABASE */}
          <div style={{
            background: '#F0FDF4',
            borderRadius: '14px',
            border: '1px solid #BBF7D0',
            padding: '18px 20px',
            display: 'flex',
            flexDirection: 'column',
            gap: '12px'
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <h4 style={{ fontSize: '13px', fontWeight: 800, color: '#15803D', margin: 0, display: 'flex', alignItems: 'center', gap: '6px' }}>
                <span>👤</span> AUTHORIZED STAFF DATABASE
              </h4>
              <button style={{
                background: '#059669',
                color: '#FFFFFF',
                border: 'none',
                borderRadius: '6px',
                padding: '4px 10px',
                fontSize: '10px',
                fontWeight: 800,
                cursor: 'pointer'
              }}>
                + REGISTER FACE
              </button>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
              {authorizedStaff.map((staff) => (
                <div key={staff.id} style={{
                  background: '#FFFFFF',
                  borderRadius: '10px',
                  padding: '10px 14px',
                  border: '1px solid #86EFAC',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between'
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                    <div style={{ background: '#10B981', color: '#FFF', borderRadius: '50%', width: '28px', height: '28px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 800, fontSize: '12px' }}>
                      {staff.name[0]}
                    </div>
                    <div>
                      <h5 style={{ margin: 0, fontSize: '13px', fontWeight: 700, color: '#14532D' }}>{staff.name}</h5>
                      <span style={{ fontSize: '11px', color: '#15803D' }}>{staff.role}</span>
                    </div>
                  </div>

                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <span style={{ fontSize: '10px', background: '#F3F4F6', padding: '2px 6px', borderRadius: '4px', color: '#4B5563', fontWeight: 600 }}>📇 1</span>
                    <span style={{ fontSize: '10px', color: '#15803D', fontWeight: 800 }}>● {staff.status}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>


          {/* Card 4: REAL-TIME IDENTIFICATION LOG */}
          <div style={{
            background: '#FEFCE8',
            borderRadius: '14px',
            border: '1px solid #FEF08A',
            padding: '18px 20px',
            display: 'flex',
            flexDirection: 'column',
            gap: '10px'
          }}>
            <h4 style={{ fontSize: '13px', fontWeight: 800, color: '#A16207', margin: 0, display: 'flex', alignItems: 'center', gap: '6px' }}>
              <span>📜</span> REAL-TIME IDENTIFICATION LOG
            </h4>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '6px', fontSize: '11px' }}>
              {identificationLogs.map((log, idx) => (
                <div key={idx} style={{ display: 'flex', gap: '8px', color: log.type === 'warning' ? '#B45309' : '#854D0E', padding: '4px 0', borderBottom: idx !== identificationLogs.length - 1 ? '1px dashed #FDE047' : 'none' }}>
                  <span style={{ fontFamily: 'monospace', fontWeight: 700 }}>{log.time}</span>
                  <span>{log.text}</span>
                </div>
              ))}
            </div>
          </div>

        </div>

      </div>
    </div>
  );
};
